os:
- linux
- windows
vm:
  size: 2x-large
language: go
go:
- 1.19.x
- 1.18.x
addons:
  apt:
    packages:
    - rpm
env:
- GO111MODULE=on
go_import_path: github.com/nats-io/nats-streaming-server
install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    go install honnef.co/go/tools/cmd/staticcheck@latest;
    go install github.com/client9/misspell/cmd/misspell@latest;
  fi
services:
- mysql
before_script:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    GO_LIST=$(go list ./... | grep -v "/spb");
    go install;
    $(exit $(go fmt $GO_LIST | wc -l));
    go vet $GO_LIST;
    find . -type f -name "*.go" | grep -v "/spb/" | xargs misspell -error -locale US;
    staticcheck $GO_LIST;
  fi
script:
- set -e
- if [[ $TRAVIS_TAG ]]; then go test -v -run=TestVersionMatchesTag ./server; fi
- if [[ ! $TRAVIS_TAG ]]; then
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      if [[ "$TRAVIS_GO_VERSION" =~ 1.18 ]]; then
        go build;
      else
        mysql -u root -e "CREATE USER 'nss'@'localhost' IDENTIFIED BY 'password'; GRANT ALL PRIVILEGES ON *.* TO 'nss'@'localhost'; CREATE DATABASE test_nats_streaming;";
        go test -v -p=1 ./... -count=1 -vet=off -failfast;
      fi;
    fi;
  fi
- if [[ ! $TRAVIS_TAG ]]; then
    if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      if [[ "$TRAVIS_GO_VERSION" =~ 1.18 ]]; then
        go build;
      else
        go install;
        go test -v -p=1 ./... -count=1 -vet=off -sql=false -failfast;
      fi;
    fi;
  fi
- set +e

deploy:
  provider: script
  cleanup: true
  script: curl -sL http://git.io/goreleaser | bash
  on:
    tags: true
    condition: ("$TRAVIS_OS_NAME" = "linux") && ("$TRAVIS_GO_VERSION" =~ "1.19")
